# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: AWS example workflow
on:
  - push
  - workflow_dispatch
env:
  BUCKET_NAME : "apero-wordpress-test-bucket-terraform-dev"
  AWS_REGION : "us-west-2"
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::666646760889:role/apero-github-oidc-role-wordpress
          role-session-name: github-actions-test
          aws-region: ${{ env.AWS_REGION }}
      - name:  Copy wordpress from s3
        run: |
          aws deploy push \
            --application-name WordPress_App \
            --s3-location s3://${{env.BUCKET_NAME}}/WordPressApp.zip \
            --ignore-hidden-files
      - name:  Deploy wordpress from s3
        run: |
          aws deploy create-deployment \
          --application-name wordpress \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name wordpress \
          --s3-location bucket=${{ env.BUCKET_NAME }},bundleType=zip,key=WordPressApp.zip
